name: Lua and Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Lua and LuaSocket
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          sudo luarocks install luasocket luafilesystem lua-cjson

      - name: Run Lua Socket Server
        run: |
          lua server.lua &

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clone cypress-example-todomvc
        run: git clone https://github.com/cypress-io/cypress-example-todomvc.git cypress-example-todomvc

      - name: Install Dependencies
        run: |
          cd cypress-example-todomvc
          npm install

      - name: Run Cypress Tests
        run: |
          cd cypress-example-todomvc
          npm run cypress:run
          # npm run cypress:run:chrome

      - name: Stop Lua Socket Server
        run: pkill lua
